theme: jekyll-theme-minimal
title: CHERKAOUI SCORE
description: A template website for Cherkaoui score
show_downloads: True
navigation:
  - title: Example
    url: example
  - title: Reados
    url: README
