theme: jekyll-theme-minimal
title: ADA Template Website yay
description: A template website for ADA yay
show_downloads: True
navigation:
  - title: Example
    url: example
  - title: Reados
    url: README
